import NextDocument, { Html, Head, Main, NextScript } from 'next/document'
import { getCssText } from 'stitches'

export default class Document extends NextDocument {
  render () {
    return (
      <Html lang="en">
        <Head>
          <title>Pokedex</title>
          {/* <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" /> */}
          <style id="stitches" dangerouslySetInnerHTML={{ __html: getCssText() }} />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}
