import type { NextPage } from 'next'
import Head from 'next/head'
import PokemonList from 'components/PokemonList'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    // eslint-disable-next-line react/react-in-jsx-scope
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PokemonList />
    </div>
  )
}

export default Home
